version: '3.3'
services:
  api_server:
    build:
      context: .
    container_name: api_container
    image: apidocker
    environment:
      - ASPNETCORE_URLS=http://+:80
    ports:
      - "5000:80"
  db_server:
    container_name: api_db_container
    image: "mcr.microsoft.com/mssql/server:2017-latest"
    environment:
      SA_PASSWORD: "myPass123"
      ACCEPT_EULA: "Y"
    ports:
      # Currently a different port, because I have another process using 1433 on my host:
      - "1432:1433"