version: '3.3'
services:
  api_server:
    build:
      context: .
    container_name: api-docker-container
    image: apidocker
    environment:
      - ASPNETCORE_URLS=http://+:80
    ports:
      - "5000:80"
  db_server:
    image: "mcr.microsoft.com/mssql/server:2017-latest"
    environment:
      SA_PASSWORD: "myPass123"
      ACCEPT_EULA: "Y"
    ports:
      - "1433:1433"